# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: PR Checks

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - uses: actions/checkout@v3

    - name: Restore node_modules
      id: cache-node_modules-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          ./node_modules
        key: node_modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('./package-lock.json') }}
        
    - run: npm install
    - run: npm run build

    - name: Save node_modules
      id: cache-node_modules-save
      uses: actions/cache/save@v3
      with:
        path: |
          ./node_modules
        key: node_modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('./package-lock.json') }}
        
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - uses: actions/checkout@v3

    - name: Restore node_modules
      id: cache-node_modules-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          ./node_modules
        key: node_modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('./package-lock.json') }}
        
    - run: npm install
    - run: npm test

    - name: Save node_modules
      id: cache-node_modules-save
      uses: actions/cache/save@v3
      with:
        path: |
          ./node_modules
        key: node_modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('./package-lock.json') }}

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - uses: actions/checkout@v3

    - name: Restore node_modules
      id: cache-node_modules-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          ./node_modules
        key: node_modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('./package-lock.json') }}
        
    - run: npm install
    - run: npm lint

    - name: Save node_modules
      id: cache-node_modules-save
      uses: actions/cache/save@v3
      with:
        path: |
          ./node_modules
        key: node_modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('./package-lock.json') }}


