# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: PR Checks

on:
  push:
    branches: [ "main" ]
  pull_request:

env:
  NODE_VERSION: 18

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        
    - uses: actions/checkout@v3

    - name: Restore node_modules
      id: cache-node_modules-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          ./node_modules
        key: node_modules-${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('./package-lock.json') }}
        
    - if: steps.cache-node_modules-restore.outputs.cache-hit != 'true'
      run: npm install
    - run: npm run build

    - name: Save node_modules
      id: cache-node_modules-save
      uses: actions/cache/save@v3
      with:
        path: |
          ./node_modules
        key: node_modules-${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('./package-lock.json') }}
        
  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - uses: actions/checkout@v3

    - name: Restore node_modules
      id: cache-node_modules-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          ./node_modules
        key: node_modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('./package-lock.json') }}
        
    - run: npm run test

  lint:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - uses: actions/checkout@v3

    - name: Restore node_modules
      id: cache-node_modules-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          ./node_modules
        key: node_modules-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('./package-lock.json') }}
        
    - run: npm run lint

